spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fitness_erp
    username: root
    password: java1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fitness.erp.domain

server:
  port: 8080